### ISSUE TITLE
Some defects

### ISSUE THREAD

**Issue by LovelyBuggies** [kjaisingh/nba-salary-predictor#1]
Although it is an amzaing job, some defects exist in your work.

- First, in the data processing peroid, I think you didn't `merge` well. For instance, Anthony Tolliver has two team id. (And if I implement as follows -- `player_stat_1 = player_stat_2017.drop_duplicates())`, he seems to occupy two rows, where he has different team id in the second row.
- Second, I see the pairplot you draw, and I strongly recommend you to have a better illustration on the insights of this.
- Third, you adopt `statmodels` to implement the **Linear Regression**, however, have you ever think about to use `sklearn` to implement the job? I think by this way, your job will be more congurous.

By the way, I want refer your work as mine. **I would indicate yours as resource**, do you agree with that? I you are interested, I would also be willing to pull you a request for the further implementation using ANNs.

**Comment by kjaisingh** [comment]
Apologies for the late reply! I will certainly look into resolving these defects, and am more than happy to have you refer to my work.
